digix_homepage:
    path:     /
    defaults: { _controller: DigixBundle:Home:display }

digix_wall:
    path:     /wall
    defaults: { _controller: DigixBundle:Wall:displayWall }

digix_loginCheck:
    path:     /logincheck
    defaults: { _controller: DigixBundle:Login:checkLogin }

digix_logout:
    path:     /logout
    defaults: { _controller: DigixBundle:Login:logout }

account_reg_check:
    path:     /registercheck
    defaults: { _controller: DigixBundle:Register:register }

facebook_login_controller:
    path:     /facebook-login
    defaults: { _controller: DigixBundle:Facebook:index }

twitter_login_controller:
    path:     /twitter-login
    defaults: { _controller: DigixBundle:Twitter:index }

google_login_controller:
    path:     /google-login
    defaults: { _controller: DigixBundle:GooglePlus:index }

flickr_login_controller:
    path:     /flickr-login
    defaults: { _controller: DigixBundle:Flickr:index }

youtube_login_controller:
    path:     /youtube-login
    defaults: { _controller: DigixBundle:Youtube:index }

display_modal_controller:
    path:     /modal
    defaults: { _controller: DigixBundle:Wall:displayModal }

tag_controller:
    path:     /tag
    defaults: { _controller: DigixBundle:Tag:tag }

search_controller:
    path:     /search
    defaults: { _controller: DigixBundle:Search:displaySearch }

search_action:
    path:     /search-action
    defaults: { _controller: DigixBundle:Search:search }

about_page:
    path:     /about
    defaults: { _controller: DigixBundle:AboutPage:displayAboutPage }

box_page:
    path:     /box
    defaults: { _controller: DigixBundle:MyBox:displayMyBox }

edit_profile_page:
    path:     /edit-profile
    defaults: { _controller: DigixBundle:ProfilePage:displayProfileEditPage }

edit_profile_page_update:
    path:     /edit-profile-update
    defaults: { _controller: DigixBundle:ProfilePage:saveChanges }

contact_page:
    path:     /contact
    defaults: { _controller: DigixBundle:ContactPage:displayContactPage }

sendmail_page: 
    path: /contact-send 
    defaults: { _controller: DigixBundle:ContactPage:sendmail }